require: rubocop-rspec

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - 'spec/dummy/**/*'
  TargetRubyVersion: 2.5

Style/FrozenStringLiteralComment:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/Documentation:
  Enabled: true
Metrics/BlockLength:
  ExcludedMethods:
    - class_methods
  Exclude:
    - 'spec/**/*'
Metrics/LineLength:
  Max: 130 # default is 80
Metrics/MethodLength:
  Max: 15 # 10 is the default
Metrics/ModuleLength:
  Max: 200 # 100 is the default
Metrics/AbcSize:
  Max: 20 # 15 is the default
Style/ClassAndModuleChildren:
  Enabled: false
Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

RSpec/MultipleExpectations:
  Enabled: false
