AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
  TargetRubyVersion: 2.6

Style/FrozenStringLiteralComment:
  Enabled: false
Style/StringLiterals:
  Enabled: false
